---
title: "650 Project"
author: "Jess"
date: "11/28/2021"
output: html_document
---

### Loading data and preprocessing
```{r}
#load packages
library(ggplot2)
library(car)
library(interactions)
library(NHANES)
library(dplyr)

dat<-NHANES

dat<-dat[!is.na(dat$BPSysAve)&!is.na(dat$BMI)&!is.na(dat$Age)&!is.na(dat$Gender)&!is.na(dat$Race1)&!is.na(dat$Education)&!is.na(dat$PhysActive)&!is.na(dat$Diabetes)&!is.na(dat$SmokeNow)&!is.na(dat$AlcoholYear)&!is.na(dat$DirectChol),] #2636
```

```{r}
dat_black = dat[dat$Race1=="Black", ]
dat_hispanic = dat[dat$Race1=="Hispanic", ]
dat_mexican = dat[dat$Race1=="Mexican", ]
dat_white = dat[dat$Race1=="White", ]
dat_other = dat[dat$Race1=="Other", ]

ggplot(dat_black, aes(x=BMI, y=BPSysAve)) + 
  geom_point()
ggplot(dat_hispanic, aes(x=BMI, y=BPSysAve)) + 
  geom_point()
ggplot(dat_mexican, aes(x=BMI, y=BPSysAve)) + 
  geom_point()
ggplot(dat_white, aes(x=BMI, y=BPSysAve)) + 
  geom_point()
ggplot(dat_other, aes(x=BMI, y=BPSysAve)) + 
  geom_point()


dat %>%
     ggplot(aes(x=BMI, 
               y=BPSysAve, 
               color=Race1))+
     geom_smooth(method="lm", level=0.3)
```


### Unadjusted analysis (BMI as POI) (log transformation to get better linearity)
```{r}
model_0<-lm(BPSysAve~BMI,data=dat)
summary(model_0)

# linearity
avPlots(model_0)
```

### Adjusted analysis 
##### adding some covariates in groups, in a sequential pattern
```{r}
#Demographic
model_1<-lm(BPSysAve~log(BMI)+
              Age+Gender+Race1+Education,data=dat)
summary(model_1)

# linearity
avPlots(model_1)
```

```{r}
#Health
model_2<-lm(BPSysAve~BMI+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol,data=dat)
summary(model_2)

# linearity
avPlots(model_2)
```


###  Adjusted analysis with interaction
```{r}
#interaction terms:
model_3<-lm(BPSysAve~BMI+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_3)

# linearity
avPlots(model_3)
```


```{r}
model_4<-lm(BPSysAve~BMI+I(BMI^2)+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_4)

# linearity
avPlots(model_4)
```

```{r}
# interaction terms

model_5<-lm(BPSysAve~BMI+log(BMI)+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_5)

# linearity
avPlots(model_5)
```

```{r}
# interaction terms

model_6<-lm(BPSysAve~BMI+sqrt(BMI)+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_6)

# linearity
avPlots(model_6)
```

##### Plot the interaction effect
```{r}
library(interactions)
#BMI*Race
interact_plot(model_5, pred = BMI, modx=Race1)
```

```{r}
#Age*Gender
interact_plot(model_5, pred = Age, modx=Gender)
```

```{r}
#DirectChol*Diabetes
interact_plot(model_5, pred = DirectChol, modx=Diabetes)
```

```{r}
#BMI Race*Gender
cat_plot(model_5, pred = BMI, modx = Gender, mod2 = Race1, geom = "line", interval = F)
```

```{r}
#BMI Race*Education
cat_plot(model_5, pred = BMI, modx = Education, mod2 = Race1, geom = "line", interval = F)
```




### Variance Stabilizing transformation (VST)
```{r}

model_7<-lm(log(BPSysAve)~BMI+log(BMI)+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_7)

# linearity
avPlots(model_7)
```

```{r}

model_8<-lm(sqrt(BPSysAve)~BMI+log(BMI)+
              Age+Gender+Race1+Education+
              PhysActive+Diabetes+SmokeNow+AlcoholYear+DirectChol+
              Age*Gender+BMI*Race1+DirectChol*Diabetes+Gender*Race1+Race1*Education, data=dat)
summary(model_8)

# linearity
avPlots(model_8)
```

```{r}
# SBP = BMI+log(BMI)
p_eq_var_1 = ggplot() + 
  geom_point(aes(y = model_5$residuals, x = model_5$fitted.values)) + 
  labs( x = "Predicted Value", y = "Residuals", title = "Residuals vs Fitted values") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(aes(y = model_5$residuals, x = model_5$fitted.values), method='lm')
p_eq_var_1

# log(SBP) = BMI+log(BMI)
p_eq_var_2 = ggplot() + 
  geom_point(aes(y = model_7$residuals, x = model_7$fitted.values)) + 
  labs( x = "Predicted Value", y = "Residuals", title = "Residuals vs Fitted values") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(aes(y = model_7$residuals, x = model_7$fitted.values), method='lm')
p_eq_var_2

# sqrt(SBP) = BMI+log(BMI)
p_eq_var_3 = ggplot() + 
  geom_point(aes(y = model_8$residuals, x = model_8$fitted.values)) + 
  labs( x = "Predicted Value", y = "Residuals", title = "Residuals vs Fitted values") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(aes(y = model_8$residuals, x = model_8$fitted.values), method='lm')
p_eq_var_3
```

